name: Build My React App

on: 
  push:
    branches: [ main ]


jobs:
  build-react-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.1.0
      - name: Setup Node JS
        uses: actions/setup-node@v6.5.0
        with:
          node-version: 22.x
          cache: 'npm'
      - name: Install Dependencies
        working-directory: ./Frontend
        run: npm install
        
      - name: Build React App
        working-directory: ./Frontend
        run: npm run build

      - name: Upload Build On Artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: React app build
          path: Frontend/dist
    
